/****** Object:  Table [dbo].[DB_LOGGER] ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DB_LOGGER]') AND type in (N'U'))
DROP TABLE [dbo].[DB_LOGGER]
GO


/****** Object:  Table [dbo].[DB_LOGGER]    ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[DB_LOGGER](
	[DB_LOGGER_ID] [int] IDENTITY(1,1) NOT NULL,
	[LOG_TYPE] [varchar](20) NULL,
	[CREATION_DATE][datetime] NULL,
	[LOG_MESSAGE] [varchar](4000) NULL,
 CONSTRAINT [PK_DB_LOGGER] PRIMARY KEY CLUSTERED 
(
	[DB_LOGGER_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO